export const config = {
  BotName: "Neura Sama",
  OwnerName: "dimasyoga",
  Version: "1.2b",
  prefix: ".",
  restapi: {
    waifu: "https://api.waifu.im/images",
    maid: "https://api.waifu.im/images?ExcludedTags=maid",
    milf: "https://api.waifu.im/images?ExcludedTags=milf",
    toram: "http://neurapi.mochinime.cyou/api/",
    neura: "https://neuraapi.vercel.app/api/toram",
  },
  thumbnail: [
    "https://i.pinimg.com/736x/16/46/ee/1646eef2bf7003c46eb1c0ac6aa6e16e.jpg",
    "https://i.pinimg.com/736x/f5/37/29/f5372928b53a4f87fc59ef26503c78e3.jpg",
    "https://i.pinimg.com/736x/8b/af/cf/8bafcf125c91b32e1acd6fabd7ce880c.jpg",
    "https://i.pinimg.com/736x/79/58/df/7958df7914871b93ee70516e678d5dd4.jpg",
    "https://i.pinimg.com/1200x/5d/73/6b/5d736b28582176b1e7f023c4c615b0b5.jpg",
  ],
  message: {
    notAdmin: "Admin Only",
    botNotadmin: "bot not admin",
    notFound: "what you are looking for is not found",
    invalid: "Your format is wrong, please check again.",
    succes: "data added successfully",
    edits: "data has been edited successfully",
    error: "An error occurred on the server. Please try again.",
    mute: "user successfully muted",
    unmute: "user successfully unmuted",
    ban: "you can't use this because you're banned",
    create: "party raid successfully created",
    allready: "the data already exists",
  },
  kerang: [
    "ya",
    "mungkin",
    "tidak",
    "mungkin saja",
    "tidak mungkin",
    "ya bisa jadi",
    "semoga saja",
    "tidak akan",
    "coba lagi",
    "ya pasti",
    "agak ragu",
    "...",
  ],
  owner: "179573169848377@lid",
};
const thumbnails = (config?.thumbnail ?? []).filter(Boolean);
export const thumbnail =
  thumbnails[Math.floor(Math.random() * thumbnails.length)];
